# Generated by Django 3.2 on 2023-01-20 03:46

import django.db.models.deletion
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230119_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={
                'verbose_name': 'Жанры произведений',
                'verbose_name_plural': 'Жанры произведений',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                unique=True,
                validators=[reviews.validators.slug_validator],
                verbose_name='Slug категории',
            ),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(
                unique=True,
                validators=[reviews.validators.slug_validator],
                verbose_name='Slug жанра',
            ),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='reviews.genre',
                verbose_name='Жанр',
            ),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='reviews.title',
                verbose_name='Произведение',
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='titles',
                to='reviews.category',
                verbose_name='Категория произведения',
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(
                through='reviews.GenreTitle',
                to='reviews.Genre',
                verbose_name='Жанры произведения',
            ),
        ),
    ]
