# Generated by Django 3.2 on 2023-01-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230120_1346'),
        ('reviews', '0003_auto_20230124_1727'),
        ('reviews', '0003_user_unique_username_email'),
    ]

    operations = []
