# Generated by Django 3.2 on 2023-01-25 02:31

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_genres_title_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[reviews.validators.name_title_validator],
                verbose_name='Название произведения',
            ),
        ),
    ]
