# Generated by Django 3.2 on 2023-01-26 09:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20230126_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={
                'ordering': ('-pub_date',),
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(
                help_text="Comment's author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to=settings.AUTH_USER_MODEL,
                verbose_name='author',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='Date of comment publication',
                verbose_name='pub_date',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(
                help_text="Review that is comment's subject",
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='reviews.review',
                verbose_name='review',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(
                help_text='Text of comment', verbose_name='text'
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(
                help_text="Review's author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to=settings.AUTH_USER_MODEL,
                verbose_name='author',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='Publication date',
                verbose_name='pub_date',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(
                help_text="Review's title score",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Score can not be less than one.'
                    ),
                    django.core.validators.MaxValueValidator(
                        10, 'Score can not be more than ten.'
                    ),
                ],
                verbose_name='score',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(
                help_text="Review's text", verbose_name='text'
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(
                help_text="Title of review's subject",
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='reviews.title',
                verbose_name='title',
            ),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(
                fields=('author', 'title'), name='only_one_review'
            ),
        ),
    ]
