# Generated by Django 3.2 on 2023-01-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_name'),
        ('reviews', '0009_auto_20230126_1253'),
    ]

    operations = [
    ]
